#!/bin/sh

# execute vector_optimizer script
chmod +x ./.github/scripts/vector_optimizer.sh
./.github/scripts/vector_optimizer.sh

# Compare git diff --exit-code status code with 0
if git diff --quiet --exit-code; then
  # If there are no differences, print "Hola!"
  echo "pre-commit: All vectors seems optimized :)"
  exit 0
else
  # If there are differences, print an error message
  echo "pre-commit: Aborting commit due to unoptimized vectors found. Please review them"
  exit 1
fi