name: Size Metrics

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "master", "main", "release/*", "feature/*" ]

jobs:
  build:
    name: Build apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Generate shorter github.sha for head branch
        id: head-short-sha
        uses: actions/github-script@v6
        run: |
          chmod +x ./.github/scripts/commit_short_sha.sh
          shortSha=$(./.github/scripts/commit_short_sha.sh)
          echo "result=${shortSha}" >> $GITHUB_OUTPUT

      - name: Build Debug APK for head branch and rename it to match head-short-sha result
        run: |
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ steps.head-short-sha.outputs.result }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{steps.head-short-sha.outputs.result}}
          path: app/build/outputs/apk/debug/${{ steps.head-short-sha.outputs.result }}.apk

      - name: Checkout base (PR target) branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Generate shorter github.sha for base branch
        id: base-short-sha
        uses: actions/github-script@v6
        run: |
          chmod +x ./.github/scripts/commit_short_sha.sh
          shortSha=$(./.github/scripts/commit_short_sha.sh)
          echo "result=${shortSha}" >> $GITHUB_OUTPUT

      - name: Build Debug APK for base branch and rename it to match base-short-sha result
        run: |
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ steps.base-short-sha.outputs.result }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{steps.base-short-sha.outputs.result}}
          path: app/build/outputs/apk/debug/${{ steps.base-short-sha.outputs.result }}.apk
