# This is a basic workflow to help you get started with Actions

name: Size Metrics

on:
  push:
  pull_request:
    branches: [ "master", "main", "release/*", "feature/*" ]

jobs:
  build:
    name: Build apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

    
