name: Size Metrics

# cancel in-progress workflow if new commits are pushed to same head branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "master", "main", "release/*", "feature/*" ]

jobs:
  build:
    name: Build apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      # this step is optional if you don't use JDK 17 as ubuntu-latest runner already
      # has java setup which defaults to JDK 11
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # this step is optional and should be added in case you get "Failed to install the following
      # Android SDK packages as some licences have not been accepted" error
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # setup cache so that every build trigger doesn't require downloading all the
      # dependencies used in project again and again saving tonnes of time
      - name: Setup Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}

      - name: Generate shorter github.sha for head branch
        id: head-short-sha
        run: |
          chmod +x ./.github/scripts/commit_short_sha.sh
          short_sha=$(./.github/scripts/commit_short_sha.sh)
          echo "head_short_sha=${short_sha}" >> $GITHUB_ENV

      - name: Build Debug APK for head branch and rename it to match head-short-sha result
        run: |
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ env.head_short_sha }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.head_short_sha }}.apk
          path: app/build/outputs/apk/debug/${{ env.head_short_sha }}.apk

      - name: Checkout base (PR target) branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}

      - name: Generate shorter github.sha for base branch
        id: base-short-sha
        run: |
          chmod +x ./.github/scripts/commit_short_sha.sh
          short_sha=$(./.github/scripts/commit_short_sha.sh)
          echo "base_short_sha=${short_sha}" >> $GITHUB_ENV

      - name: Build Debug APK for base branch and rename it to match base-short-sha result
        run: |
          ./gradlew assembleDebug
          mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/${{ env.base_short_sha }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.base_short_sha }}.apk
          path: app/build/outputs/apk/debug/${{ env.base_short_sha }}.apk