name: Spotless

# cancel in-progress workflow if new commits are pushed to same head branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "master", "main", "release/*", "feature/*" ]

jobs:
  check:
    name: Spotless Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Apk Build Setup
        uses: ./.github/workflows/apk-build-setup

      - name: Run Spotless Check
        run: |
          ./gradlew spotlessCheck --no-configuration-cache