name: Vector Optimizer

on:
  pull_request:
    branches: [ "master", "main", "release/*", "feature/*" ]

jobs:
  optimizer:
    name: Vector Optimizer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install avocado tool by Alex Lockwood
        run: npm install -g avocado

      - name: Optimizes Vector Drawables
        run: |
          chmod +x ./.github/scripts/vector_optimizer.sh
          ./.github/scripts/vector_optimizer.sh
        shell: bash

      - name: Generate shorter github.sha for head branch
        id: short-sha
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const headSha = git rev-parse HEAD
            return headSha.substring(0,7)

      - name: Create optimize-vectors branch
        run: |
          git config --global user.email "akash.mercer@gmail.com"
          git config --global user.name "Akash Khunt"
          git checkout -b optimize-vectors-${{ steps.short-sha.outputs.result }}
          git push --set-upstream origin optimize-vectors-${{ steps.short-sha.outputs.result }}

      - name: Open PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'vectors optimized'
          title: 'Vectors optimized'
          body: 'Vectors drawables optimized using avocado tool'
          branch: optimize-vectors-${{ steps.short-sha.outputs.result }}
          base: master
