name: Vector Optimizer

on:
  pull_request:
    branches: [ "master", "main", "release/*", "feature/*" ]

jobs:
  optimizer:
    name: Vector Optimizer
    runs-on: ubuntu-latest

    env:
      DRAWABLE_COUNT: ${{ steps.drawable-checker.outputs.result }}
      SHORT_SHA: ${{ steps.short-sha.outputs.result }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install avocado tool by Alex Lockwood
        run: npm install -g avocado

      # here we run our custom script which navigates to drawable directories of different modules
      # of "known" modularization strategy
      - name: Optimizes Vector Drawables
        run: |
          chmod +x ./.github/scripts/vector_optimizer.sh
          ./.github/scripts/vector_optimizer.sh
        shell: bash

      # this steps puts the count of optimized vector drawables (using git diff) in step's output
      - name: Check if any Vector Drawables were optimized
        id: drawable-checker
        run: |
          chmod +x ./.github/scripts/drawable_changes_checker.sh
          drawableCount=$(./.github/scripts/drawable_changes_checker.sh)
          echo "result=${drawableCount}" >> $GITHUB_OUTPUT
        shell: bash

      # generate a shorter 7 character SHA (from head branch) which we'll use as
      # a suffix to new PR branch
      - name: Generate shorter github.sha for head branch
        id: short-sha
        if: ${{ DRAWABLE_COUNT != '0' }}
        run: |
          chmod +x ./.github/scripts/commit_short_sha.sh
          shortSha=$(./.github/scripts/commit_short_sha.sh)
          echo "result=${shortSha}" >> $GITHUB_OUTPUT
        shell: bash

      - name: Create optimize-vectors branch
        if: ${{ DRAWABLE_COUNT != '0' }}
        run: |
          git config --global user.email "akash.mercer@gmail.com"
          git config --global user.name "Akash Khunt"
          git checkout -b optimize-vectors-${{ SHORT_SHA }}
          git push --set-upstream origin optimize-vectors-${{ SHORT_SHA }}

      - name: Open PR
        if: ${{ DRAWABLE_COUNT != '0' }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'vectors optimized'
          title: 'Vectors optimized'
          body: 'Vectors drawables optimized using avocado tool'
          branch: optimize-vectors-${{ SHORT_SHA }}
          base: ${{ github.head_ref }}
