name: Vector Optimizer

on:
  push:
  pull_request:
    branches: [ "master" ]

env:
  BRANCH_NAME: ${{ github.sha }}

jobs:
  optimizer:
    name: Optimizer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install avocado tool by Alex Lockwood
        run: npm install -g avocado
        
      - name: Create optimize-vectors branch
        run: |
          git config --global user.email "akash.mercer@gmail.com"
          git config --global user.name "Akash Khunt"
          git checkout -b "$BRANCH_NAME"
          git push --set-upstream origin "$BRANCH_NAME"
        
      - name: Optimizes Vector Drawables
        run: |
          chmod +x ./.github/scripts/vector_optimizer.sh
          ./.github/scripts/vector_optimizer.sh
        shell: bash
      
      - name: Open PR
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'vectors optimized'
          title: 'Vectors optimized'
          body: 'Vectors optimized'
          branch: "$BRANCH_NAME"
          base: master
