name: Vector Optimizer

on:
  pull_request:
    branches: [ "master", "main", "release/*", "feature/*" ]

jobs:
  optimizer:
    name: Vector Optimizer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Install avocado tool by Alex Lockwood
        run: npm install -g avocado

      # here we run our custom script which navigates to drawable directories of different modules
      # of "known" modularization strategy
      - name: Optimizes Vector Drawables
        run: |
          chmod +x ./.github/scripts/vector_optimizer.sh
          ./.github/scripts/vector_optimizer.sh
        shell: bash

      # this steps puts the count of optimized vector drawables (using git diff) in step's output
      - name: Check if any Vector Drawables were optimized
        id: drawable-checker
        run: |
          chmod +x ./.github/scripts/drawable_changes_checker.sh
          drawable_count=$(./.github/scripts/drawable_changes_checker.sh)
          echo "drawable_count=${drawable_count}" >> "$GITHUB_ENV"
        shell: bash

      # generate a shorter 7 character SHA (from head branch) which we'll use as
      # a suffix to new PR branch
      - name: Generate shorter github.sha for head branch
        id: short-sha
        if: ${{ env.drawable_count != '0' }}
        run: |
          chmod +x ./.github/scripts/commit_short_sha.sh
          short_sha=$(./.github/scripts/commit_short_sha.sh)
          echo "short_sha=${short_sha}" >> "$GITHUB_ENV"
        shell: bash

      - name: Create optimize-vectors branch
        if: ${{ env.drawable_count != '0' }}
        run: |
          git config --global user.email "akash.mercer@gmail.com"
          git config --global user.name "Akash Khunt"
          git checkout -b optimize-vectors-${{ env.short_sha }}
          git push --set-upstream origin optimize-vectors-${{ env.short_sha }}

      - name: Open PR
        if: ${{ env.drawable_count != '0' }}
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'vectors optimized'
          title: 'Vectors optimized'
          body: Vectors drawables optimized using avocado tool for PR - #${{ github.event.issue.number }}
          branch: optimize-vectors-${{ env.short_sha }}
          base: ${{ github.head_ref }}